import "./globals.css"
import type {Metadata} from "next"
import {Noto_Sans_Myanmar} from "next/font/google"
import Layout from "./components/Layout"
import mtk from "../../public/mintheinkha_logo.png"
const mmFont = Noto_Sans_Myanmar({
    weight: "400",
    style: "normal",
    subsets: ["myanmar"],
})

export const metadata: Metadata = {
    title: "လက်ထောက်ဗေဒင်",
    description: "Generated by create next app",
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <head>
                <link rel="shortcut icon" href="/mtk.png" type="image/png" />
            </head>
            <body className={mmFont.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    )
}
